services:
  - type: web
    name: rankquest-backend
    runtime: docker
    dockerfilePath: ./Backend/Dockerfile
    dockerContext: ./Backend
    healthCheckPath: /health
    envVars:
      - key: JWT_SECRET
        generateValue: true

      - key: JWT_EXPIRATION
        value: 86400000

      - key: DATABASE_URL
        sync: false

      - key: DATABASE_USERNAME
        sync: false

      - key: DATABASE_PASSWORD
        sync: false

      - key: GOOGLE_CLIENT_ID
        sync: false

      - key: CORS_ORIGIN
        sync: false
